### DISCUSSION TITLE
Idea: Old Scratch 2.0 UI

### DISCUSSION THREAD

**Discussion by GoldcatGames** [ScratchAddons/ScratchAddons#3871] [Ideas]
This Has Been Something I've Been Thinking Of For 3 Years, Adding Back The Old 2.0 UI, Like The Old Homepage, The Old Logo, The Old Font, The Old Buttons And Much More.

Reference: [https://web.archive.org/web/20150704020532/https://scratch.mit.edu/](https://web.archive.org/web/20150704020532/https://scratch.mit.edu/)

**Comment by Samq64** [comment]
Duplicate of #985.

**Comment by kccuber-scratch** [comment]
There's the customizable blocks size addon, the customizable block color addon, the scratch 2.0 preset in the dark mode addon, so at least the editor looks like 2.0... kind of. the font is still missing but should be easy to add in

**Reply by kccuber-scratch** [reply]
Okay, so I came up with some CSS that makes the font the old one.. here it is. you can use with some browser extension that allows you to use custom css.
``` css
text.blocklyText {
  font-family: Lucida Grande,Verdana,Arial,DejaVu Sans,sans-serif;
  font-weight: 700;
  font-size: 10pt;
  word-spacing: +1px;
}

blocklyDropdownText, g.blocklyEditableText text.blocklyText, input.blocklyHtmlInput {
  font-family: Lucida Grande,Verdana,Arial,DejaVu Sans,sans-serif;
  font-weight: 400;
  font-size: 9pt !important;
}
```
EDIT: Oh and here's a screen shot (project is griffpatch's MMO platformer)
![image](https://user-images.githubusercontent.com/92891642/145723505-0a4807cc-c22b-4487-99ab-d30f1b815f84.png)
Make sure use the custom block size addon with the 2.0 preset and zoom in a bit.
