### DISCUSSION TITLE
3.0 Boxes

### DISCUSSION THREAD

**Discussion by daniel4-scratch** [ScratchAddons/ScratchAddons#4189] [Ideas]
The boxes on the main page and every where still look 2.0 style. So i was wondering if this bit of code could go into the 2.0 to 3.0 addon.
```css

/* splash.css | https://scratch.mit.edu/splash.css */

.box .box-header {
  /* border-top: 1px solid white; */
}

.box {
  /* border-radius: 10px 10px 0 0; */
  border-radius: 10px;
}

.box .box-content {
  border-radius: 10px;
}
```
Before
![Screenshot 2022-02-05 at 12-42-25 Scratch - Imagine, Program, Share](https://user-images.githubusercontent.com/65277548/152623971-644d7854-9f6e-4cee-98c2-7372435cf666.png)
After
![Screenshot 2022-02-05 at 12-38-50 Scratch - Imagine, Program, Share](https://user-images.githubusercontent.com/65277548/152623942-df841484-8e17-4425-88b4-6fcc5404c872.png)
