### DISCUSSION TITLE
Is `displayNoneWhileDisabled` actually useful?

### DISCUSSION THREAD

**Discussion by mxmou** [ScratchAddons/ScratchAddons#4825] [Ideas]
A lot of addons use `addon.tab.displayNoneWhileDisabled` to hide their UI when disabled. It would often be simpler to add something like
```js
element.style.display = "none";
```
to the userscript and
```css
.element {
  display: something !important;
}
```
to a userstyle. This is already the only option if there are other conditions for showing the element, for example if a setting has to be enabled. It also makes the code cleaner because `display: something` is defined in the same place as the rest of the CSS.

My suggestion is to remove `displayNoneWhileDisabled` and always do this. A potential downside is that a userstyle is needed but most addons that add their own UI already have a userstyle.

**Comment by WorldLanguages** [comment]
I agree that the current way is pretty bad. TurboWarp for example, ignores the second argument because instead of using CSS variables, it adds a new class to the element AFAIK (I never looked deeply into how it does it). Having to specify `{display: "flex"}` in the JS in addition to CSS is bad.

@mxmou If you believe you found the best way to solve this you can go ahead and send a pull request. I guess this considers the case when addons want to hide an element even when the addon is enabled, right? Would it be an `!important` war in that case?

Final comment:

> A lot of addons use `addon.tab.displayNoneWhileDisabled` to hide their UI when disabled. It would often be simpler to add something like
> 
> ```js
> element.style.display = "none";
> ```

I believe a code comment or something is missing there - by reading that code I might think the button is intended to be hidden, but it's just for dynamicEnable and dynamicDisable. Maybe we could have a specific function like `addon.tab.displayNone(element)` for better code readibility? I haven't thought much about this (we need to release v1.26.1 quick lol) so take my opinion with a grain of salt

**Reply by mxmou** [reply]
> I guess this considers the case when addons want to hide an element even when the addon is enabled, right? Would it be an `!important` war in that case?

An addon like that can do either
```css
.element:not(.hidden) {
  display: something !important;
}
```
or
```css
.element {
  display: something !important;
}
.element.hidden {
  display: none !important;
}
```

> I believe a code comment or something is missing there - by reading that code I might think the button is intended to be hidden, but it's just for dynamicEnable and dynamicDisable. Maybe we could have a specific function like `addon.tab.displayNone(element)` for better code readibility? I haven't thought much about this (we need to release v1.26.1 quick lol) so take my opinion with a grain of salt

`forum-search` already uses this method and it has the following comment:
```js
searchContent.style.display = "none"; // overridden by userstyle if the addon is enabled
```

`addon.tab.displayNone` still doesn't make it obvious why the element has to be hidden so I think a comment is better.

**Reply by WorldLanguages** [reply]
Sounds good. You can send a pull request if you plan to work on this now, or if not, please create an issue.

**Reply by mxmou** [reply]
I'll open a PR soon.

**Reply by WorldLanguages** [reply]
@mxmou The use of `!important` everywhere has caused confusing comments on the Discord server. Here's another idea inspired by how TurboWarp does it.

Could you say if this proposed solution has any drawbacks? This one doesn't require setting the display property on the JS, and it changes less existing code.

`addon.tab.displayNoneWhileDisabled` continues to exist. It simply adds a `data-addon-disabled-[addonId]` attribute to the element.
If the addon is dynamically disabled, a new `<style>` element is added at the bottom of the `<head>` with contents:
```css
[data-addon-disabled-turbowarp-player] {
  display: none !important;
}
```
If the addon is enabled, such CSS rule disappears from the DOM.
This could also be done with classes, but I think a data attribute is harder to accidentally remove.

**Reply by mxmou** [reply]
That's a good solution too. It doesn't work if `!important` is already needed for a different reason but in that case the userstyle method can still be used.

**Reply by WorldLanguages** [reply]
> It doesn't work if `!important` is already needed for a different reason

Could you give us an example?

**Reply by mxmou** [reply]
> > It doesn't work if `!important` is already needed for a different reason
> 
> Could you give us an example?

In addon A:
```js
addon.tab.displayNoneWhileDisabled(element);
```

```css
.element {
  display: block;
}

.element.more-specific-selector {
  display: inline;
}
```

In addon B:
```css
.element.more-specific-selector {
  /* !important is used to override addon A but it also breaks displayNoneWhileDisabled */
  display: flex !important;
}
```

That's also a problem in the current implementation of `displayNoneWhileDisabled` though, and I don't think it currently affects any addon.
