### DISCUSSION TITLE
My styling for the forums

### DISCUSSION THREAD

**Discussion by Steve0Greatness** [ScratchAddons/ScratchAddons#4843] [Show and tell]
In my opinion, the forums using 2.0 to 3.0 are kinda ugly. No offense. I have a few problems with the entire option as a whole(when it comes to the forums).

1. Some links are styled like buttons for some reason.
2. Both of the options for how the posts will look don't look incredible, and differ from what I like the forums to look like.

However, this can easily be solved with a bit of CSS(this is a User Style BTW).

```css
:root {
	--header-color: #064734;
}
.linkst li:not(:last-child) a, .linksb li:not(:last-child) a, .pagination span, .pagination a {
	background-color: transparent !important;
	color: var(--darkWww-link) !important;
	border: none !important;
	padding: 0 !important;
}
.linkst li:not(:last-child) a:hover, .linksb li:not(:last-child) a:hover, .pagination span:hover, .pagination a:hover {
	color: var(--darkWww-link-hover) !important;
}
.postright::before {
	display: none !important;
}
.postfootright > ul {
	border-bottom-left-radius: 0 !important;
	border-bottom: none !important;
}
.postmsg {
	border-top-right-radius: 0 !important;
	border-top: none !important;
}
.postmsg {
	border-top-right-radius: 0 !important;
	border-top: none !important;
}
.postleft {
	margin-top: 15px;
}
.firstpost .box .box-head {
	background-color: var(--header-color) !important;
	padding: 8px;
	border: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-top-right-radius: 5px;
	border-top-left-radius: 5px;
}
.firstpost .box .box-head .conr, .firstpost .box .box-head a, .pagination span.current, .pagination span.current:hover {
	color: #fff !important;
}
.postsignature hr {
	display: none !important;
}
.postsignature {
	border-top: 1px var(--darkWww-border-20) solid;
	padding-top: 5px;
	margin-top: 5px;
}
.firstpost .box .box-content {
	border-left: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-top: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-bottom: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-bottom-right-radius: 5px;
	border-bottom-left-radius: 5px;
	padding-left: 15px;
}
#reply .box-head {
	border: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-top-right-radius: 5px !important;
	padding: 5px !important;
	background-color: var(--darkWww-box, white) !important;
	border-top-left-radius: 5px !important;
}
#reply .box-content {
	border: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-top: none !important;
	padding: 10px !important;
	border-bottom-right-radius: 5px !important;
	padding-bottom: 15px !important;
	border-bottom-left-radius: 5px !important;
}
.pagination .disabled {
	opacity: 1 !important;
	color: #fff !important;
}
.pagination .disabled:hover {
	opacity: 0.75 !important;
	color: #fff !important;
}
#reply .box-head h4 {
	margin: 5px !important;
}
.breadcrumb_rss {
	filter: grayscale() invert() brightness(3);
}
.blockpost.searchposts .postmsg {
	border-bottom-left-radius: 0 !important;
	border-bottom: none !important;
}
.blockpost.searchposts .box-content {
	border: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-right: none !important;
	border-bottom-left-radius: 5px !important;
}
.blockpost.searchposts .box-head {
	border: 1px solid var(--darkWww-border, rgba(0, 0, 0, 0.1)) !important;
	border-bottom: none !important;
	padding: 8px;
	background-color: var(--header-color) !important;
	border-top-left-radius: 5px !important;
	border-top-right-radius: 5px !important;
}
.blockpost.searchposts .box-head, .blockpost.searchposts .box-head a {
	color: #fff !important;
}
.blockpost.searchposts .postleft {
	margin-left: 15px;
}
```

This, at least in my opinion, looks way better than how it can look. It elevates both of my problems with the current 2.0 to 3.0 look of the forums, and a little bit more... for some reason.

Encase you want screenshots:

![How topics look](https://user-images.githubusercontent.com/75220768/179411514-fbecfe8d-79c4-4524-9115-0cb6c8eb6599.png)
Taken on [min and max operators](https://scratch.mit.edu/discuss/topic/594712/)

![How forum sections look](https://user-images.githubusercontent.com/75220768/179411517-e5f01164-88e5-46d9-ad25-a7faa55530da.png)

![A bit more of topics](https://user-images.githubusercontent.com/75220768/179411845-fa5c16be-3c92-46f6-a634-01e1bdb1096c.png)
Taken on the same topic

Is this the right place?

_Edit: It doesn't look right without dark mode, the color of the forums header should be stored in a variable. Not sure why it isn't._
_Edit2: Why I mean by that is that the top of the posts don't match the header._
_Edit 3: Until the forum header's color is stored in a variable, you'll need to update it manually. I've added a few new lines to the top of the CSS under `:root`, there's a variable there called `--header-color`. If your browser(or OS in general) has a eyedropper tool, use it to get the forum header's color(if you're using an OS/browser that doesn't have this capability, you will need to go into inspect element to get the color); once you have it, replace `#064734` with the color you got._
