### DISCUSSION TITLE
Switch to using issue forms

### DISCUSSION THREAD

**Discussion by DNin01** [ScratchAddons/ScratchAddons#5013] [Ideas] [answered]
This request is not for the Scratch Addons browser extension, but some of the repository's configuration files.

I was just wondering if you would like to upgrade your [issue templates](https://github.com/ScratchAddons/ScratchAddons/tree/master/.github/ISSUE_TEMPLATE) to [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). They're currently in beta, but also pretty cool - you fill out forms _in a UI_ like [this](https://docs.github.com/assets/cb-61019/images/help/repository/sample-issue-form.png).

I can get issue forms ready if you think it would be cool to have a UI for forms. I will also _slightly_ rework the templates if you wouldn't mind. If you don't need that or this isn't important right now, I'm perfectly okay with that. The issue templates you already have act as good enough forms. I just thought it was worth a shot, plus, I'm just looking after the user experience, especially as SA grows!

We can also discuss this to find the ideal issue form, how much they would help, and whether we should use them or stick with templates.

Pros:
- Forms might be easier to follow
- We can _require_ certain fields to be filled out to encourage constructive suggestions and bug reports

Cons:
- You _have_ to stick with the forms, unlike templates which you can just erase and freely write, unless you open a blank issue or edit your issue later, which might make it harder to create more in-depth suggestions.

Here's a sample of the YAML file for a New addon issue form (if you have any feedback, let me know and I'll take it into account when I make the PR):
```
name: ➕ New addon
description: Suggest a new addon!
labels: ["new addon", "scope: addon", "type: enhancement"]
body:
  - type: markdown
    attributes:
      value: **READ BEFORE CREATING!**

  - type: markdown
    attributes:
      value: |
        - Avoid creating duplicates! Read the FAQ page and search through Issues and Discussions before creating one.
        - Try to make a simple but descriptive title, and include the detailed information below.
        - Make sure to use the latest version of Scratch Addons.
        - Asking for help should be done on Discussions or our Discord server. Return to the last page for the links.

  - type: markdown
    attributes:
      value: |
        FAQ: https://scratchaddons.com/faq
        Return to the last page: https://github.com/ScratchAddons/ScratchAddons/issues/new/choose

  - type: textarea
    id: problem
    attributes:
      label: Why this would be helpful/solve a problem
      description: A clear and concise description of how this addon could help with a problem or how it could improve something.
      placeholder: Sometimes I want to...
    validations:
      required: true

  - type: textarea
    id: howitworks
    attributes:
      label: What this addon does
      description: A clear and concise description of how the features this addon provides work and what they do.
      placeholder: This addon adds a button to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Possible alternatives
      description: A clear and concise description of any alternative solutions or features you've thought about or heard of.
      placeholder: We could also ... instead.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Demonstration(s) and additional context
      description: Add any other information like screenshots, videos, or context about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: check
    attributes:
      label: Check for duplicates
      description: Remember to search to make sure the idea hasn't been suggested already. If you found a duplicate, add your feedback there instead.
      options:
        - label: I've checked for duplicates.
          required: true
```

~~These will also be my first ever issue forms!~~ I made one in a testing repo already, but there was an error that I don't understand. I might need some help.
