### DISCUSSION TITLE
Visual changes to the setting switches

### DISCUSSION THREAD

**Discussion by DNin01** [ScratchAddons/ScratchAddons#5643] [Ideas]
I've been having some fun with the switches in the settings page, and I thought someone else might like one of these changes.

### New colors for the off-state switch

Mostly to improve the contrast. The background of the black switch is kind of hard to see.

**Dark theme:**
```css
:root {
  --switch-background: #5f5f5f;
  --switch-inner-background: #fff;
}
```

**Light theme:**
```css
:root {
  --switch-background: #7f7f7f;
  --switch-inner-background: #fff;
}
```

![Slightly higher contrast switches](https://user-images.githubusercontent.com/106490990/213318780-47a6bf1b-25fc-47f4-b255-10c32b4a7aa2.png)

### Glowing setting switches (only when hovering)

For, um... engagement?

```css
.switch:hover {
  filter: drop-shadow(0px 0px 5px var(--switch-background));
}

.switch[state="on"]:hover {
  filter: drop-shadow(0px 0px 5px var(--brand-orange));
}

input.setting-input.check:checked:hover {
  filter: drop-shadow(0px 0px 5px var(--blue));
}

input.setting-input.check:hover {
  filter: drop-shadow(0px 0px 5px var(--switch-background));
}
```

![Glowing switches](https://user-images.githubusercontent.com/106490990/213318793-7a333d03-f2fe-46d4-bf7a-981ec019ee50.png)

Perhaps one or more of these could make their way into SA?
