### DISCUSSION TITLE
Why some css animation not work?

### DISCUSSION THREAD

**Discussion by OriLiMu** [ScratchAddons/ScratchAddons#7653] [Help] [answered]
Here is my code find-references folder in addons.  Not lastest code I am working on it may do some change on it. 
https://github.com/woshichuanqilz/ScratchAddons/tree/23e6804e0134d9f142461cff35c0b24b69e27ab9

# First
rotate fa icon not work for me . The code is [here](https://github.com/woshichuanqilz/ScratchAddons/blob/23e6804e0134d9f142461cff35c0b24b69e27ab9/addons/find-references/userstyle.css#L191)

```css
.sa-fr-input-wrapper label i {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
  color: #e1a91a;
  background-color: white;
  transform: scale(4);
  transition: transform 0.5s ease, background-color 0.5s ease;
}

.sa-fr-input-wrapper label i:hover {
  background-color: #855cd6; /* 鼠标悬停时改变颜色 */
  transform: rotate(360deg); /* 保持旋转360度和放大效果 */
}
```

# Second
I have the css code for animation: 
You can check it [here](https://github.com/woshichuanqilz/ScratchAddons/blob/23e6804e0134d9f142461cff35c0b24b69e27ab9/addons/find-references/userstyle.css#L346)
```css
#floatWindow {
  /* width: 300px; */
  /* height: 300px; */
  position: absolute;
  top: 20%;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  z-index: 100;
  display: flex;
  flex-direction: column;
  border-radius: 10px;
  overflow-x: hidden;
  overflow-y: hidden;
  scrollbar-width: thin;
  scrollbar-color: #2ca5e2 transparent;
  transition: width 0.5s;
}

.search_icon:hover + #floatWindow {
  animation-name: expandWidth;
  animation-duration: 0.5s;
  animation-fill-mode: forwards;
}

@keyframes expandWidth {
  0% {
    width: var(--sa-fr-bar-height);
  }
  100% {
    width: 300px;
  }
}
```
