### ISSUE TITLE
Account Settings capitalization.

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#1154]
**Is your feature request related to a problem? Please describe.**

LLK/scratch-www#4731
LLK/scratch-www#4771
https://scratch.mit.edu/discuss/topic/461302/

People want "Account **S**ettings fixed.

**The fix**

It's very easy! It's CSS - not even JavaScript!

```css
.account-nav .dropdown, ul.user-nav {
    text-transform: capitalize;
}
```

One problem: this is kinda small for its own addon...
