### ISSUE TITLE
"Become a Scratcher" modal in own profile unreadble with dark-www

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2166]
![image](https://user-images.githubusercontent.com/17484114/114793476-d6237000-9d60-11eb-9afe-e4b90c7a98ae.png)

Fix (tested successfully):
```css
#scratcher-promotion-wrapper {
  color: black;
}
```
