### ISSUE TITLE
The forum search bar is too wide

### ISSUE THREAD

**Issue by Norbiros** [ScratchAddons/ScratchAddons#4740]
### Description

Forum search form is too long, so it looks strange with Scratchcr.

### Reproduction steps

1. Enable forum search addon
2. Go to any topic in forums

### Screenshots

![Screenshot 2022-06-30 at 15-21-20 Scratch - Imagine, Program, Share](https://user-images.githubusercontent.com/89837724/176687280-1e43db65-4990-4944-b8de-4706cd26460d.png)

### Environment

- Browser: Firefox Dev
- Scratch Addons version: newest
- Operating system: Linux Gentoo

### Additional context

How to fix it in inspector:
```css
#forum-search-form {
  display: block !important;
}

#forum-search-input {
    width: calc(75% - 8px);
}
```
