### ISSUE TITLE
Find bar animation

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4897]
### Is your request related to a problem? Please describe.

The find bar doesn't have any animation, so it it doesn't feel very smooth when focusing it, especially on big projects.

### Describe the solution you'd like

Fade the find bar menu in and out when focusing the find box.

### Describe alternatives you've considered

Some other kind of animation.

**Comment by Secret-chest** [comment]
Fading wouldn't make any sense. Maybe it should be like Cinnamon menus.

Example:

```css
@keyframes open {
    from {
        transform: scale(1, 0);
    to {
        transform: scale(1, 1);
}
@keyframes close {
    from {
        transform: scale(1, 1);
    to {
        transform: scale(1, 0);
}
```
