### ISSUE TITLE
Highlight mentions

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6185]
### Why this would be helpful

This would make it easier to see mentions of your username.

### How this addon works

This addon would highlight mentions of your username in comments and forum posts.
![A comment with two replies, one of them is a reply to me, my username is highlighted in orange](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/cde7399c-23dd-415a-ad4a-1abecfafc13e)

GitHub has this feature built in.

**Comment by DNin01** [comment]
Here's what I came up with:
```css
.comment-content > a[href="/users/D-ScratchNinja"] {
    background-color: #ff9500;
    border-radius: 4px;
    color: #fff;
    padding: 2px;
}
```
If only there was a way to insert anyone's username so others can actually use it. CSS variables don't seem to work in selectors.
