### ISSUE TITLE
Fix blurry running blocks (glow effect) somehow

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6872]
### Why this would be helpful

Related #4438 #3677 #3690

This is a vanilla Scratch bug that through time was experienced in all desktop browsers

### How this addon works

Scratch has had this bug for years now. We could provide a bug fix, or at least a way to change the running glow effect filter for another filter, so that the user can sacrifice the good-looking glow filter for a more basic one which doesn't cause blurring.

### Additional context

Someone on Discord made a small CSS userstyle that changes the effect and fixes the blur:

https://github.com/ScratchAddons/ScratchAddons/assets/17484114/35e646ad-ee62-406d-8d2b-b92ba2aae3e6

```css
	@keyframes dash-anim {
  		to {
  		  stroke-dashoffset: 20;
 		 }
	}
	
	
	g[filter*='url(#blocklyStackGlowFilter'] {
		
		filter: none;	
		
> path,
		g:not([data-shapes*='argument']):not([data-shapes*='reporter']) > path {
			
			animation: dash-anim 0.5s linear infinite;
			
			stroke-width: 0.2rem;
			stroke-dasharray: 10;
			stroke-linecap: round;
		}		
	}
	
```
