### ISSUE TITLE
Automate the abandoned label

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7199]
### Why this would be helpful

We have a https://github.com/ScratchAddons/ScratchAddons/labels/status%3A%20abandoned label but since it has to be applied manually it isn't that useful.

### My suggestion

Add an action to the GitHub bot that automatically adds the label. I was thinking after 6 months of inactivity and maybe longer if the PR has an assignee. PRs with more than 1 org approvals would never be marked as abandoned.

### Possible alternatives

Adding the label manually or closing the PRs.

**Comment by Hans5958** [comment]
We can expand [the Stale action](https://github.com/ScratchAddons/ScratchAddons/blob/master/.github/workflows/stale-issues.yml) to add another type of label. In paper this should only label PRs with no assignees with the appropritate labels. I can't find the way to ignore approved ones.

```
      - name: Execute Action
        uses: actions/stale@v6
        with:
          stale-pr-message: '[insert message that says that it is abandoned]'
          days-before-stale: -1
          days-before-close: -1
          days-before-pr-stale: 360
          stale-pr-label: 'status: abandoned'
          operations-per-run: 30
          exempt-all-pr-assignees: true
          repo-token: ${{ steps.generate-token.outputs.token }}
 ```
