### ISSUE TITLE
addon.self.dir for userstyles

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#741]
Non-theme userstyles are injected with `<link>` elements, so the URLs specified in `url()` CSS functions are relative to the URL of the userstyle. However, theme userstyles are injected as `<style>`s lose this information, so `url()`s end up being relative to the URL of the document.
We could add a special string like `%addon-self-dir%` or similar, that gets replaced on userstyles (both themes and non-themes) to the value of `addon.self.dir` for that addon. Example use:
```css
element {
  background-image: url(%addon-self-dir%/background.png);
}
```
