### ISSUE TITLE
Add 2.0 Style Block Bevel Filter to editor-theme3

### ISSUE THREAD

**Issue by ZenithRogue** [ScratchAddons/ScratchAddons#7789]
### Why this would be helpful

I am a big fan of the Scratch 2.0 style. By borrowing the block SVG filters found at https://scratchblocks.github.io/,  i have been able to pretty seamlessly transpose this block style.

## My Current CSS:
```css
.blocklyPath {
    filter: url(#bevelFilter);
}
g[data-shapes="argument"] > path.blocklyPath.blocklyBlockBackground,
g[data-argument-type="text"] > path.blocklyPath.blocklyBlockBackground,
g[data-argument-type="text number"] > path.blocklyPath.blocklyBlockBackground,
g[data-argument-type="variable"] > path.blocklyPath.blocklyBlockBackground,
path[data-argument-type="boolean"],
g.blocklyEditableText:has(rect.blocklyBlockBackground),
g[data-argument-type="dropdown"]:has(path.blocklyPath.blocklyBlockBackground) {
    filter: url(#inputBevelFilter);
}
g[data-argument-type="dropdown"] > path.blocklyPath.blocklyBlockBackground,
rect.blocklyBlockBackground {
    filter: url(#inputDarkFilter);
}
g[data-shapes="c-block c-1 hat"] > g[data-shapes="stack"]:not(.blocklyDraggable)  > path.blocklyPath.blocklyBlockBackground {
    filter: none;
    stroke: #FFF4;
    fill: none;
    stroke-width: 3px
}
text.blocklyText {
    font-family: Lucida Grande,Verdana,Arial,DejaVu Sans,sans-serif;
    font-weight: 700;
    font-size: 10pt;
    word-spacing: +1px;
}
```
## Preview
![image](https://github.com/user-attachments/assets/54d9534d-50d1-43d0-8559-ee6af0d809af)
I will note that I am using a combination of other addons to achieve this style, namely `Customizable block shape`, and `Customizable block text style`

### Additional context

I'm not quite sure if i will make this update to `editor-theme3` myself yet, I just don't have time at this exact moment
